### ISSUE TITLE
random-js inside the haggle.js is missed

### ISSUE THREAD

**Issue by MindfulMe** [hola/challenge_haggling#11]
```
Error: Cannot find module 'random-js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rostyslav/projects/hola/src/haggle.js:4:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

````

**Comment by MindfulMe** [comment]
Solved by running ``` npm i ```
